name: 🚀 LazyLogic Static Deploy to Netlify (Optimized)
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v3
      - name: ⚙️ Install html-minifier and terser
        run: |
          sudo apt-get update -y
          sudo apt-get install -y npm
          npm install -g html-minifier-terser clean-css-cli terser
      - name: 🧹 Minify HTML, CSS, JS
        run: |
          find public -name '*.html' -exec html-minifier-terser --collapse-whitespace --remove-comments --minify-js true --minify-css true -o {} {} \;
          find public -name '*.css' -exec cleancss -o {} {} \;
          find public -name '*.js' -exec terser -c -m -o {} -- {} \;
      - name: 🚀 Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./public
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: 🧩 Post-Build Enhancements
        run: bash scripts/postbuild.sh
   - name: 📱 Send NTFY notification (success)
     if: success()
     run: |
       curl -d "✅ LazyLogic deploy successful — branch ${{ github.ref_name }} deployed successfully." \
       -H "Title: LazyLogic Deploy Success" \
       -H "Priority: high" \
       -H "Tags: rocket,coffee,white_check_mark" \
       -H "Click: https://lazylogic.netlify.app" \
       https://ntfy.sh/lazylogic-global

   - name: ⚠️ Send NTFY notification (failure)
     if: failure()
     run: |
       curl -d "❌ LazyLogic deploy failed on branch ${{ github.ref_name }} — check logs." \
       -H "Title: LazyLogic Deploy Failed" \
       -H "Priority: urgent" \
       -H "Tags: warning,skull" \
       -H "Click: https://github.com/${{ github.repository }}/actions" \
       https://ntfy.sh/lazylogic-global
